apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: blrk/webapp-backend:1.0.0 
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret  # Name of your Kubernetes Secret
                  key: FLASK_SECRET_KEY
            - name: DATABASE_HOST
              value: "mydb-postgres-service"  # Important: Use the service name
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "mydatabase"
            - name: DATABASE_USER
              value: "myuser"
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Name of your PostgreSQL Secret
                  key: POSTGRES_PASSWORD
          livenessProbe: # Add liveness and readiness probes
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

