apiVersion: v1
kind: Service
metadata:
  name: login-app-backend # Changed service name
  namespace: mtvlabk8su1 # Change to the namespace where you deployed your app
spec:
  selector:
    app: login-app #  Selector should match the app label in your Deployment
  ports:
    - protocol: TCP
      port: 80 #  Port the service exposes.  Typically, you'd expose this
      targetPort: 5000 # The port your container listens on
