apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: mtvlabk8su1
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-data-dir
          image: busybox
          command:
            - /bin/sh
            - -c
            - rm -rf /var/lib/postgresql/data/* || true; mkdir -p /var/lib/postgresql/data
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: "postgres:15"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "postgres-secret"
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
  volumeClaimTemplates: # Define this for StatefulSets
  - metadata:
      name: postgres-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

